### PR TITLE
Au3Check -

### PR DESCRIPTION
**Pull request by mlipok**
Checked with Au3Check and Tidy

### CODE REVIEW

**Comment by genius257** [comment]
* indentation should be with spaces (4 per indentation)
* line 3 to 8 should be removed

**Comment by mlipok** [comment]
Why with 4xSpace and not with @TAB ?

**Comment by genius257** [comment]
It's a personal preference of mine.
Also it better for readability on GitHub.

The most important reason is that your current pull request has `588 changes`. If indention preference remains unchanged, your pull request only has `34 changes`

**Comment by mlipok** [comment]
Please decline this PullRequest.
I'll make a new one when I'm ready.

**Comment by genius257** [comment]
Okay, looking forward to it. :smile:

**Pull request closed without merging**
